#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "✨ Running pre-commit checks..."
npm run lint

if [ $? -ne 0 ]; then
  echo "❌ Linting failed! Please fix the errors before committing."
  exit 1
fi

echo "✅ Pre-commit checks passed!"
